{% set version = "0.10.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-performance
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/performance_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/performance/performance_{{ version }}.tar.gz
  sha256: 0b66d18829a6f09ff9692ffba2db3c9f12e39f5f1fdd2bcf0e74c0137c39dd97

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bayestestr >=0.9.0
    - r-datawizard
    - r-insight >=0.14.0
  run:
    - r-base
    - r-bayestestr >=0.9.0
    - r-datawizard
    - r-insight >=0.14.0

test:
  commands:
    - $R -e "library('performance')"           # [not win]
    - "\"%R%\" -e \"library('performance')\""  # [win]

about:
  home: https://easystats.github.io/performance/
  license: GPL-3.0-only
  summary: Utilities for computing measures to assess model quality, which are not directly provided by R's 'base' or 'stats' packages. These  include e.g. measures like r-squared, intraclass correlation coefficient (Nakagawa, Johnson & Schielzeth (2017) <doi:10.1098/rsif.2017.0213>),  root mean squared error or functions
    to check models for overdispersion,  singularity or zero-inflation and more. Functions apply to a large variety of regression models, including generalized linear models, mixed effects models and Bayesian models.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: performance
# Type: Package
# Title: Assessment of Regression Models Performance
# Version: 0.3.0
# Date: 2019-08-05
# Authors@R: c( person("Daniel",  "Ludecke",  role = c("aut", "cre"),  email = "d.luedecke@uke.de",  comment = c(ORCID = "0000-0002-8895-3206")), person("Dominique",  "Makowski",  email = "dom.makowski@gmail.com", role = c("aut", "ctb"),  comment = c(ORCID = "0000-0001-5375-9967")), person("Philip",  "Waggoner",  email = "philip.waggoner@gmail.com", role = c("aut", "ctb"),  comment = c(ORCID = "0000-0002-7825-7573")) )
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: Utilities for computing measures to assess model quality, which are not directly provided by R's 'base' or 'stats' packages. These  include e.g. measures like r-squared, intraclass correlation coefficient (Nakagawa, Johnson & Schielzeth (2017) <doi:10.1098/rsif.2017.0213>),  root mean squared error or functions to check models for overdispersion,  singularity or zero-inflation and more. Functions apply to a large variety of regression models, including generalized linear models, mixed effects models and Bayesian models.
# URL: https://easystats.github.io/performance/
# BugReports: https://github.com/easystats/performance/issues
# Depends: R (>= 3.0)
# Imports: insight (>= 0.4.1), bayestestR (>= 0.2.2)
# Suggests: AER, betareg, brms, covr, glmmTMB, ICS, ICSOutlier, lavaan, lme4, loo, Matrix, MASS, mlogit, nlme, ordinal, parallel, pscl, psych, randomForest, rmarkdown, rstanarm, rstantools, see (>= 0.2.1), survival, testthat
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-08-05 11:41:47 UTC; mail
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>), Dominique Makowski [aut, ctb] (<https://orcid.org/0000-0001-5375-9967>), Philip Waggoner [aut, ctb] (<https://orcid.org/0000-0002-7825-7573>)
# Repository: CRAN
# Date/Publication: 2019-08-05 12:50:06 UTC
